# 重新生成 YAML 格式完全符合規範的 environment.yml
correct_environment_yml = """\
name: catdog-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - tensorflow
    - matplotlib
    - numpy
"""

file_path = "/mnt/data/environment.yml"
with open(file_path, "w", encoding="utf-8") as f:
    f.write(correct_environment_yml)

file_path
